djangoblog/urls.py
from django.contrib import admin
from django.urls import path
from myblog import views
from django.conf.urls import  include



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('myblog.urls')),
    path('', include('comments.urls'))
]

myblog/urls.py
from django.urls import path
from myblog import views

app_name = 'myblog'
urlpatterns = [
    # path('', views.index, name='index'),

    path('', views.IndexView.as_view(), name='index'),
    path('posts/<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('archives/<int:year>/<int:month>/', views.ArchiveView.as_view(), name='archive'),
    path('categories/<int:pk>/', views.CategoryView.as_view(), name='category'),
    path('tags/<int:pk>/', views.TagView.as_view(), name='tag'),

]

templates/blog/inclusions/_archives.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="widget widget-archives">
  <h3 class="widget-title">归档</h3>
  <ul>
    {% for date in date_list %}
      <li>
        <a href="{% url 'myblog:archive' date.year date.month %}">
         {{ date.year }} 年 {{ date.month }} 月
        </a>
      </li>
    {% empty %}
      暂无归档！
    {% endfor %}
  </ul>
</div>
</body>
</html>

templates/blog/inclusions/_categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="widget widget-category">
  <h3 class="widget-title">分类</h3>
  <ul>
    {% for category in category_list %}
      <li>
        <a href="{% url 'myblog:category' category.pk %}">{{ category.name }} <span class="post-count">(13)</span></a>
      </li>
    {% empty %}
      暂无分类！
    {% endfor %}
  </ul>
</div>
</body>
</html>

templates/blog/inclusions/_recent_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="widget widget-recent-posts">
  <h3 class="widget-title">最新文章</h3>
  <ul>
    {% for post in recent_post_list %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
      </li>
    {% empty %}
      暂无文章！
    {% endfor %}
  </ul>
</div>
</body>
</html>

templates/blog/inclusions/_tags.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="widget widget-tag-cloud">
  <h3 class="widget-title">标签云</h3>
  <ul>
    {% for tag in tag_list %}
      <li>
        <a href="{% url 'myblog:tag' tag.pk %}">{{ tag.name }}</a>
      </li>
    {% empty %}
      暂无标签！
    {% endfor %}
  </ul>
</div>
</body>
</html>